### ISSUE TITLE
Port to Full Kernel

### ISSUE THREAD

**Issue by blink1073** [arokem/ipython-matlabkernel#1]
Hi @arokem, I created an [Octave kernel](https://github.com/blink1073/octave_kernel) using Oct2Py that should serve as a good template for the Matlab Kernel.

**Comment by arokem** [comment]
Nice! Thanks for pointing out - maybe some day when I have time...

**Comment by blink1073** [comment]
There is actually an easier way now: https://github.com/blink1073/jupyter_kernel.  I will be porting octave_kernel over to use this.  I could take a stab at a Matlab version if you'd like.

**Comment by arokem** [comment]
Yes - not very high on my list right now, so feel free to start working on
that. Maybe I can help trying it out when you have something up, so please
do keep me in the loop about this.

**Comment by blink1073** [comment]
Will do, I do not actually have a Matlab license.
